-- =========================================================================
-- Direct messaging between portal accounts, across roles -- any signed-in
-- account can message any other, independent of the Roles & Page Access /
-- Area-scoping system (that governs data pages, not who can DM whom).
--
-- Data model: conversations (1:1 for now) <- conversation_participants
-- (who's in it + their own last_read_at, for unread counts) <- messages.
--
-- Run once, after add-admin-roles-and-areas.sql (profiles must exist).
-- Safe to re-run.
-- =========================================================================

CREATE TABLE IF NOT EXISTS "public"."conversations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "last_message_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."conversations" OWNER TO "postgres";

DO $$
BEGIN
  ALTER TABLE "public"."conversations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
      SEQUENCE NAME "public"."conversations_id_seq"
      START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  );
EXCEPTION WHEN duplicate_table THEN
  NULL;
END $$;

ALTER TABLE "public"."conversations" DROP CONSTRAINT IF EXISTS "conversations_pkey";
ALTER TABLE ONLY "public"."conversations" ADD CONSTRAINT "conversations_pkey" PRIMARY KEY ("id");


CREATE TABLE IF NOT EXISTS "public"."conversation_participants" (
    "conversation_id" bigint NOT NULL,
    "profile_id" "uuid" NOT NULL,
    "last_read_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."conversation_participants" OWNER TO "postgres";

ALTER TABLE "public"."conversation_participants" DROP CONSTRAINT IF EXISTS "conversation_participants_pkey";
ALTER TABLE ONLY "public"."conversation_participants"
    ADD CONSTRAINT "conversation_participants_pkey" PRIMARY KEY ("conversation_id", "profile_id");

ALTER TABLE "public"."conversation_participants" DROP CONSTRAINT IF EXISTS "conversation_participants_conversation_id_fkey";
ALTER TABLE ONLY "public"."conversation_participants"
    ADD CONSTRAINT "conversation_participants_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE CASCADE;

ALTER TABLE "public"."conversation_participants" DROP CONSTRAINT IF EXISTS "conversation_participants_profile_id_fkey";
ALTER TABLE ONLY "public"."conversation_participants"
    ADD CONSTRAINT "conversation_participants_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "idx_conversation_participants_profile" ON "public"."conversation_participants" USING "btree" ("profile_id");


CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" bigint NOT NULL,
    "conversation_id" bigint NOT NULL,
    "sender_id" "uuid" NOT NULL,
    "body" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "messages_body_not_blank" CHECK (length(btrim("body")) > 0)
);

ALTER TABLE "public"."messages" OWNER TO "postgres";

DO $$
BEGIN
  ALTER TABLE "public"."messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
      SEQUENCE NAME "public"."messages_id_seq"
      START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  );
EXCEPTION WHEN duplicate_table THEN
  NULL;
END $$;

ALTER TABLE "public"."messages" DROP CONSTRAINT IF EXISTS "messages_pkey";
ALTER TABLE ONLY "public"."messages" ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."messages" DROP CONSTRAINT IF EXISTS "messages_conversation_id_fkey";
ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE CASCADE;

ALTER TABLE "public"."messages" DROP CONSTRAINT IF EXISTS "messages_sender_id_fkey";
ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "idx_messages_conversation_created" ON "public"."messages" USING "btree" ("conversation_id", "created_at");


-- ---------- Helpers ----------
CREATE OR REPLACE FUNCTION "public"."is_conversation_participant"("uid" "uuid", "conv_id" bigint)
RETURNS boolean
LANGUAGE "sql"
SECURITY DEFINER
SET "search_path" = 'public'
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.conversation_participants
    WHERE conversation_id = conv_id AND profile_id = uid
  );
$$;

ALTER FUNCTION "public"."is_conversation_participant"("uuid", bigint) OWNER TO "postgres";

-- Bumps the parent conversation's last_message_at whenever a message is
-- sent, so the conversation list can sort by recent activity without a
-- separate query. SECURITY DEFINER since a sender has no UPDATE grant on
-- conversations otherwise.
CREATE OR REPLACE FUNCTION "public"."touch_conversation_on_message"()
RETURNS "trigger"
LANGUAGE "plpgsql"
SECURITY DEFINER
SET "search_path" = 'public'
AS $$
BEGIN
  UPDATE public.conversations SET last_message_at = NEW.created_at WHERE id = NEW.conversation_id;
  RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."touch_conversation_on_message"() OWNER TO "postgres";

DROP TRIGGER IF EXISTS "on_message_touch_conversation" ON "public"."messages";
CREATE TRIGGER "on_message_touch_conversation"
    AFTER INSERT ON "public"."messages"
    FOR EACH ROW EXECUTE FUNCTION "public"."touch_conversation_on_message"();

-- Finds an existing 1:1 conversation between the caller and the given
-- profile, or creates one. SECURITY DEFINER so it can insert both
-- participant rows atomically -- a plain client-side insert can't add
-- someone else as a participant under the RLS policies below.
CREATE OR REPLACE FUNCTION "public"."start_direct_conversation"("other_profile_id" "uuid")
RETURNS bigint
LANGUAGE "plpgsql"
SECURITY DEFINER
SET "search_path" = 'public'
AS $$
DECLARE
  me uuid := auth.uid();
  existing_id bigint;
  new_id bigint;
BEGIN
  IF me IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF other_profile_id = me THEN
    RAISE EXCEPTION 'Cannot start a conversation with yourself';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = other_profile_id) THEN
    RAISE EXCEPTION 'That account does not exist';
  END IF;

  SELECT cp1.conversation_id INTO existing_id
  FROM public.conversation_participants cp1
  JOIN public.conversation_participants cp2 ON cp2.conversation_id = cp1.conversation_id
  WHERE cp1.profile_id = me AND cp2.profile_id = other_profile_id
  LIMIT 1;

  IF existing_id IS NOT NULL THEN
    RETURN existing_id;
  END IF;

  INSERT INTO public.conversations DEFAULT VALUES RETURNING id INTO new_id;
  INSERT INTO public.conversation_participants (conversation_id, profile_id) VALUES
    (new_id, me),
    (new_id, other_profile_id);

  RETURN new_id;
END;
$$;

ALTER FUNCTION "public"."start_direct_conversation"("uuid") OWNER TO "postgres";

-- One-call conversation list: the other participant, last message preview,
-- and an unread count (messages after MY last_read_at, not sent by me).
CREATE OR REPLACE FUNCTION "public"."get_my_conversations"()
RETURNS TABLE (
  "conversation_id" bigint,
  "other_profile_id" "uuid",
  "other_email" "text",
  "other_full_name" "text",
  "last_message_at" timestamp with time zone,
  "last_message_body" "text",
  "last_message_sender_id" "uuid",
  "unread_count" bigint
)
LANGUAGE "sql"
SECURITY DEFINER
SET "search_path" = 'public'
STABLE
AS $$
  SELECT
    c.id,
    op.id,
    op.email,
    op.full_name,
    c.last_message_at,
    lm.body,
    lm.sender_id,
    COALESCE(uc.cnt, 0)
  FROM public.conversations c
  JOIN public.conversation_participants me_cp ON me_cp.conversation_id = c.id AND me_cp.profile_id = auth.uid()
  JOIN public.conversation_participants other_cp ON other_cp.conversation_id = c.id AND other_cp.profile_id <> auth.uid()
  JOIN public.profiles op ON op.id = other_cp.profile_id
  LEFT JOIN LATERAL (
    SELECT "body", "sender_id" FROM public.messages m
    WHERE m.conversation_id = c.id
    ORDER BY m.created_at DESC
    LIMIT 1
  ) lm ON true
  LEFT JOIN LATERAL (
    SELECT count(*) AS cnt FROM public.messages m2
    WHERE m2.conversation_id = c.id AND m2.created_at > me_cp.last_read_at AND m2.sender_id <> auth.uid()
  ) uc ON true
  ORDER BY c.last_message_at DESC;
$$;

ALTER FUNCTION "public"."get_my_conversations"() OWNER TO "postgres";


-- ---------- RLS ----------
ALTER TABLE "public"."conversations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."conversation_participants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;

-- No direct INSERT policy on conversations/conversation_participants for
-- "authenticated" -- creation only happens through start_direct_conversation()
-- (SECURITY DEFINER, bypasses RLS), which is the only safe way to add
-- someone else as a participant.
DROP POLICY IF EXISTS "Participants can view their conversations" ON "public"."conversations";
CREATE POLICY "Participants can view their conversations" ON "public"."conversations"
FOR SELECT TO "authenticated"
USING ("public"."is_conversation_participant"("auth"."uid"(), "id"));

DROP POLICY IF EXISTS "Participants can view conversation members" ON "public"."conversation_participants";
CREATE POLICY "Participants can view conversation members" ON "public"."conversation_participants"
FOR SELECT TO "authenticated"
USING ("public"."is_conversation_participant"("auth"."uid"(), "conversation_id"));

DROP POLICY IF EXISTS "Users can update their own read state" ON "public"."conversation_participants";
CREATE POLICY "Users can update their own read state" ON "public"."conversation_participants"
FOR UPDATE TO "authenticated"
USING ("profile_id" = "auth"."uid"())
WITH CHECK ("profile_id" = "auth"."uid"());

DROP POLICY IF EXISTS "Participants can view messages" ON "public"."messages";
CREATE POLICY "Participants can view messages" ON "public"."messages"
FOR SELECT TO "authenticated"
USING ("public"."is_conversation_participant"("auth"."uid"(), "conversation_id"));

DROP POLICY IF EXISTS "Participants can send messages" ON "public"."messages";
CREATE POLICY "Participants can send messages" ON "public"."messages"
FOR INSERT TO "authenticated"
WITH CHECK (
  "sender_id" = "auth"."uid"()
  AND "public"."is_conversation_participant"("auth"."uid"(), "conversation_id")
);


-- ---------- Grants ----------
GRANT ALL ON TABLE "public"."conversations" TO "authenticated";
GRANT ALL ON TABLE "public"."conversations" TO "service_role";
GRANT ALL ON SEQUENCE "public"."conversations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."conversations_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."conversation_participants" TO "authenticated";
GRANT ALL ON TABLE "public"."conversation_participants" TO "service_role";

GRANT ALL ON TABLE "public"."messages" TO "authenticated";
GRANT ALL ON TABLE "public"."messages" TO "service_role";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."start_direct_conversation"("uuid") TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_conversations"() TO "authenticated";


-- ---------- Realtime ----------
DO $$
BEGIN
  ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."messages";
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;
