-- =========================================================================
-- System-wide audit trail: who changed what, when, and the before/after
-- values -- distinct from the existing "Audit Logs" screen, which only
-- tails public training_lookup_logs (anonymous search activity on the
-- training-lookup page). This is a real change log for the app's data.
--
-- Deliberately does NOT audit "messages"/"conversations" -- that's private
-- communication content, not operational/admin data, and logging it would
-- let Admins read private DMs without consent.
--
-- Run once, after the members/pfo/clp/areas/admin migrations already
-- applied (this references those tables). Safe to re-run.
-- =========================================================================

CREATE TABLE IF NOT EXISTS "public"."audit_log" (
    "id" bigint NOT NULL,
    "table_name" "text" NOT NULL,
    "record_id" "text",
    "action" "text" NOT NULL,
    "actor_id" "uuid",
    "actor_email" "text",
    "old_data" "jsonb",
    "new_data" "jsonb",
    "changed_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "audit_log_action_check" CHECK (("action" = ANY (ARRAY['INSERT'::"text", 'UPDATE'::"text", 'DELETE'::"text", 'PAGE_VIEW'::"text"])))
);

ALTER TABLE "public"."audit_log" OWNER TO "postgres";

DO $$
BEGIN
  ALTER TABLE "public"."audit_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
      SEQUENCE NAME "public"."audit_log_id_seq"
      START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  );
EXCEPTION WHEN duplicate_table THEN
  NULL;
END $$;

ALTER TABLE "public"."audit_log" DROP CONSTRAINT IF EXISTS "audit_log_pkey";
ALTER TABLE ONLY "public"."audit_log" ADD CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."audit_log" DROP CONSTRAINT IF EXISTS "audit_log_actor_id_fkey";
ALTER TABLE ONLY "public"."audit_log"
    ADD CONSTRAINT "audit_log_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS "idx_audit_log_changed_at" ON "public"."audit_log" USING "btree" ("changed_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_audit_log_table_name" ON "public"."audit_log" USING "btree" ("table_name");
CREATE INDEX IF NOT EXISTS "idx_audit_log_actor" ON "public"."audit_log" USING "btree" ("actor_id");


-- ---------- Generic trigger ----------
-- One function reused across every audited table. record_id is derived
-- generically (tries "id", then "MemberIDNo", then composite keys) rather
-- than requiring a per-table argument, so attaching it to a new table is
-- just one CREATE TRIGGER line.
CREATE OR REPLACE FUNCTION "public"."log_audit_event"()
RETURNS "trigger"
LANGUAGE "plpgsql"
SECURITY DEFINER
SET "search_path" = 'public'
AS $$
DECLARE
  actor uuid := auth.uid();
  actor_email text;
  rec jsonb;
  rec_id text;
BEGIN
  SELECT email INTO actor_email FROM public.profiles WHERE id = actor;

  rec := CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
  rec_id := COALESCE(
    rec ->> 'id',
    rec ->> 'MemberIDNo',
    NULLIF(concat_ws(':', rec ->> 'role_id', rec ->> 'page_key'), ':'),
    NULLIF(concat_ws(':', rec ->> 'conversation_id', rec ->> 'profile_id'), ':'),
    NULLIF(concat_ws(':', rec ->> 'area_id', rec ->> 'profile_id'), ':')
  );

  INSERT INTO public.audit_log ("table_name", "record_id", "action", "actor_id", "actor_email", "old_data", "new_data")
  VALUES (
    TG_TABLE_NAME,
    rec_id,
    TG_OP,
    actor,
    actor_email,
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) ELSE NULL END
  );

  IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END;
$$;

ALTER FUNCTION "public"."log_audit_event"() OWNER TO "postgres";


-- ---------- Attach to every audited table ----------
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'members', 'pfo_members', 'clp_trainings', 'clp_training_participants',
    'areas', 'area_members', 'roles', 'pages', 'role_pages', 'profiles', 'user_areas'
  ]
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS audit_%1$s ON public.%1$s', t);
    EXECUTE format(
      'CREATE TRIGGER audit_%1$s AFTER INSERT OR UPDATE OR DELETE ON public.%1$s FOR EACH ROW EXECUTE FUNCTION public.log_audit_event()',
      t
    );
  END LOOP;
END $$;


-- ---------- RLS: Admins only ----------
ALTER TABLE "public"."audit_log" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view audit log" ON "public"."audit_log";
CREATE POLICY "Admins can view audit log" ON "public"."audit_log"
FOR SELECT TO "authenticated"
USING ("public"."is_admin"());

-- Page-view events have no underlying table row/trigger to log them, so
-- the client inserts them directly -- restricted to logging as yourself,
-- and only ever as a PAGE_VIEW (never able to fabricate an INSERT/UPDATE/
-- DELETE row for something that didn't happen).
DROP POLICY IF EXISTS "Users can log their own page views" ON "public"."audit_log";
CREATE POLICY "Users can log their own page views" ON "public"."audit_log"
FOR INSERT TO "authenticated"
WITH CHECK ("actor_id" = "auth"."uid"() AND "action" = 'PAGE_VIEW');

GRANT SELECT ON TABLE "public"."audit_log" TO "authenticated";
GRANT ALL ON TABLE "public"."audit_log" TO "service_role";


-- ---------- Register the page ----------
INSERT INTO "public"."pages" ("key", "label", "sort_order") VALUES
    ('systemAudit', 'System Audit Log', 12)
ON CONFLICT ("key") DO NOTHING;

INSERT INTO "public"."role_pages" ("role_id", "page_key")
SELECT "id", 'systemAudit' FROM "public"."roles" WHERE "name" = 'Admin'
ON CONFLICT DO NOTHING;


-- ---------- Realtime ----------
DO $$
BEGIN
  ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."audit_log";
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;
