-- =========================================================================
-- Push notifications for received chat messages. Stores one row per
-- device/token so a user signed in on multiple devices gets pushed on
-- all of them; the "send-message-notification" Edge Function (deployed
-- separately, see supabase/functions/send-message-notification) reads
-- this table with the service role after a new row lands in messages,
-- and calls the Expo Push API for every other participant's token(s).
--
-- Run once, after add-messaging.sql (profiles/messages must exist).
-- Safe to re-run.
-- =========================================================================

CREATE TABLE IF NOT EXISTS "public"."push_tokens" (
    "id" bigint NOT NULL,
    "profile_id" "uuid" NOT NULL,
    "token" "text" NOT NULL,
    "platform" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."push_tokens" OWNER TO "postgres";

DO $$
BEGIN
  ALTER TABLE "public"."push_tokens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
      SEQUENCE NAME "public"."push_tokens_id_seq"
      START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  );
EXCEPTION WHEN duplicate_table THEN
  NULL;
END $$;

ALTER TABLE "public"."push_tokens" DROP CONSTRAINT IF EXISTS "push_tokens_pkey";
ALTER TABLE ONLY "public"."push_tokens" ADD CONSTRAINT "push_tokens_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."push_tokens" DROP CONSTRAINT IF EXISTS "push_tokens_token_key";
ALTER TABLE ONLY "public"."push_tokens" ADD CONSTRAINT "push_tokens_token_key" UNIQUE ("token");

ALTER TABLE "public"."push_tokens" DROP CONSTRAINT IF EXISTS "push_tokens_profile_id_fkey";
ALTER TABLE ONLY "public"."push_tokens"
    ADD CONSTRAINT "push_tokens_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "idx_push_tokens_profile" ON "public"."push_tokens" USING "btree" ("profile_id");

-- Keeps updated_at fresh so a stale/reinstalled-app token that gets
-- re-registered visibly bumps, useful for pruning later if needed.
CREATE OR REPLACE FUNCTION "public"."touch_push_token_updated_at"()
RETURNS "trigger"
LANGUAGE "plpgsql"
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."touch_push_token_updated_at"() OWNER TO "postgres";

DROP TRIGGER IF EXISTS "on_push_token_update" ON "public"."push_tokens";
CREATE TRIGGER "on_push_token_update"
    BEFORE UPDATE ON "public"."push_tokens"
    FOR EACH ROW EXECUTE FUNCTION "public"."touch_push_token_updated_at"();


-- ---------- RLS ----------
ALTER TABLE "public"."push_tokens" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage their own push tokens" ON "public"."push_tokens";
CREATE POLICY "Users manage their own push tokens" ON "public"."push_tokens"
FOR ALL TO "authenticated"
USING ("profile_id" = "auth"."uid"())
WITH CHECK ("profile_id" = "auth"."uid"());


-- ---------- Grants ----------
GRANT ALL ON TABLE "public"."push_tokens" TO "authenticated";
GRANT ALL ON TABLE "public"."push_tokens" TO "service_role";
GRANT ALL ON SEQUENCE "public"."push_tokens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."push_tokens_id_seq" TO "service_role";
