-- =========================================================================
-- Per-portal-user Area scoping for viewing "members" (the Directory) data.
--
-- Lets an Admin assign one or more Areas to a portal user (profiles.id)
-- from the Portal Users screen. Once a user has at least one Area
-- assigned, they only see members whose members."AreaName" matches that
-- area OR any area nested underneath it (Sector -> Cluster -> Chapter). A
-- portal user with NO areas assigned stays unrestricted (sees every
-- member) -- area assignment is an opt-in narrowing tool, not a mandatory
-- gate. Admins (role name = 'Admin') always see everyone, regardless of
-- their own area assignments.
--
-- IMPORTANT: matching is a case-insensitive PREFIX match — a member is
-- visible if their "AreaName" starts with a visible area's name (e.g. Area
-- "West 1" also covers members with AreaName "West 1A", "West 1 - Unit 3",
-- etc.), same convention as the "# Members" count on the Areas screen. So
-- an Area's name just needs to be a prefix of the real AreaName values
-- already stored on members, not an exact match.
--
-- Because this restricts a real RLS policy (not just app seed data), any
-- screen that queries "members" directly -- Directory, the Dashboard's
-- member-count stats, the CLP participant search -- will all respect this
-- automatically. pfo_members is ALSO restricted the same way (see below),
-- so PFO Trainings/Reports/Stats screens only show rows for members within
-- a scoped account's visible areas. clp_training_participants is not
-- restricted yet -- ask if you want CLP Maintenance scoped the same way.
--
-- Run once, after add-admin-roles-and-areas.sql / split-admin-pages.sql.
-- Safe to re-run if something fails partway through.
-- =========================================================================


-- ---------- Which Areas a portal user can see ----------
CREATE TABLE IF NOT EXISTS "public"."user_areas" (
    "id" bigint NOT NULL,
    "profile_id" "uuid" NOT NULL,
    "area_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."user_areas" OWNER TO "postgres";

DO $$
BEGIN
  ALTER TABLE "public"."user_areas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
      SEQUENCE NAME "public"."user_areas_id_seq"
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1
  );
EXCEPTION WHEN duplicate_table THEN
  NULL;
END $$;

ALTER TABLE "public"."user_areas" DROP CONSTRAINT IF EXISTS "user_areas_pkey";
ALTER TABLE ONLY "public"."user_areas" ADD CONSTRAINT "user_areas_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."user_areas" DROP CONSTRAINT IF EXISTS "user_areas_profile_id_fkey";
ALTER TABLE ONLY "public"."user_areas"
    ADD CONSTRAINT "user_areas_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE "public"."user_areas" DROP CONSTRAINT IF EXISTS "user_areas_area_id_fkey";
ALTER TABLE ONLY "public"."user_areas"
    ADD CONSTRAINT "user_areas_area_id_fkey" FOREIGN KEY ("area_id") REFERENCES "public"."areas"("id") ON DELETE CASCADE;

ALTER TABLE "public"."user_areas" DROP CONSTRAINT IF EXISTS "user_areas_profile_id_area_id_key";
ALTER TABLE ONLY "public"."user_areas"
    ADD CONSTRAINT "user_areas_profile_id_area_id_key" UNIQUE ("profile_id", "area_id");

CREATE INDEX IF NOT EXISTS "idx_user_areas_profile" ON "public"."user_areas" USING "btree" ("profile_id");
CREATE INDEX IF NOT EXISTS "idx_user_areas_area" ON "public"."user_areas" USING "btree" ("area_id");


-- ---------- Helpers ----------
CREATE OR REPLACE FUNCTION "public"."has_area_restriction"("uid" "uuid")
RETURNS boolean
LANGUAGE "sql"
SECURITY DEFINER
SET "search_path" = 'public'
STABLE
AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_areas WHERE profile_id = uid);
$$;

ALTER FUNCTION "public"."has_area_restriction"("uuid") OWNER TO "postgres";

-- Every area name a user can see: their directly assigned areas, plus
-- every area nested underneath each one.
CREATE OR REPLACE FUNCTION "public"."visible_area_names"("uid" "uuid")
RETURNS TABLE("name" "text")
LANGUAGE "sql"
SECURITY DEFINER
SET "search_path" = 'public'
STABLE
AS $$
  WITH RECURSIVE assigned AS (
    SELECT a.id, a.name
    FROM public.user_areas ua
    JOIN public.areas a ON a.id = ua.area_id
    WHERE ua.profile_id = uid
  ),
  tree AS (
    SELECT id, name FROM assigned
    UNION
    SELECT ar.id, ar.name
    FROM public.areas ar
    JOIN tree t ON ar.parent_id = t.id
  )
  SELECT DISTINCT name FROM tree;
$$;

ALTER FUNCTION "public"."visible_area_names"("uuid") OWNER TO "postgres";


-- ---------- Restrict the Directory (members) by Area ----------
DROP POLICY IF EXISTS "Allow authenticated users to view members" ON "public"."members";
CREATE POLICY "Allow authenticated users to view members" ON "public"."members"
FOR SELECT TO "authenticated"
USING (
  "public"."is_admin"()
  OR NOT "public"."has_area_restriction"("auth"."uid"())
  OR EXISTS (
    SELECT 1 FROM "public"."visible_area_names"("auth"."uid"()) "van"
    WHERE "members"."AreaName" ILIKE "van"."name" || '%'
  )
);


-- ---------- Restrict PFO Trainings (pfo_members) by Area ----------
-- Same rule, joined through the member's own AreaName so PFO
-- screens (grid matrix, reports, stats) match the Directory.
DROP POLICY IF EXISTS "Allow authenticated users to view PFO records" ON "public"."pfo_members";
CREATE POLICY "Allow authenticated users to view PFO records" ON "public"."pfo_members"
FOR SELECT TO "authenticated"
USING (
  "public"."is_admin"()
  OR NOT "public"."has_area_restriction"("auth"."uid"())
  OR EXISTS (
    SELECT 1 FROM "public"."members" "m"
    WHERE "m"."MemberIDNo" = "pfo_members"."MemberIDNo"
      AND EXISTS (
        SELECT 1 FROM "public"."visible_area_names"("auth"."uid"()) "van"
        WHERE "m"."AreaName" ILIKE "van"."name" || '%'
      )
  )
);


-- ---------- RLS + grants for user_areas itself (Admin-managed) ----------
ALTER TABLE "public"."user_areas" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage user_areas" ON "public"."user_areas";
CREATE POLICY "Admins manage user_areas" ON "public"."user_areas" FOR ALL TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());

-- A non-admin also needs to read their OWN assignment rows -- e.g. the
-- Directory's Area filter narrows itself to the signed-in account's
-- assigned areas, which requires querying this table as that account.
DROP POLICY IF EXISTS "Users can view own area assignments" ON "public"."user_areas";
CREATE POLICY "Users can view own area assignments" ON "public"."user_areas" FOR SELECT TO "authenticated" USING ("profile_id" = "auth"."uid"());

GRANT ALL ON TABLE "public"."user_areas" TO "authenticated";
GRANT ALL ON TABLE "public"."user_areas" TO "service_role";
GRANT ALL ON SEQUENCE "public"."user_areas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_areas_id_seq" TO "service_role";
