-- =========================================================================
-- Change-approval queue for the CFC Members Directory: an account that
-- isn't an Admin or Moderator no longer writes to members directly from
-- that screen -- its edits are queued here instead, and only take effect
-- once an Admin/Moderator approves them (applying the change themselves,
-- which their own direct-write access to members already allows).
--
-- Also adds is_moderator(), a Moderator-role counterpart to the existing
-- is_admin(), and widens the existing System Audit Log's SELECT policy so
-- Moderators can read it too (needed by the new Member Change History page,
-- which reuses that same audit_log table filtered to table_name = 'members'
-- rather than a second logging system).
--
-- Run once, after add-admin-roles-and-areas.sql and add-system-audit-log.sql.
-- Safe to re-run.
-- =========================================================================

CREATE OR REPLACE FUNCTION "public"."is_moderator"()
RETURNS boolean
LANGUAGE "sql"
SECURITY DEFINER
SET "search_path" = 'public'
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    JOIN public.roles r ON r.id = p.role_id
    WHERE p.id = auth.uid() AND r.name = 'Moderator'
  );
$$;

ALTER FUNCTION "public"."is_moderator"() OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."member_change_requests" (
    "id" bigint NOT NULL,
    "member_id" "text" NOT NULL,
    "requested_by" "uuid",
    "requested_by_email" "text",
    "changes" "jsonb" NOT NULL,
    "previous_values" "jsonb" NOT NULL,
    "status" "text" DEFAULT 'pending' NOT NULL,
    "reviewed_by" "uuid",
    "reviewed_by_email" "text",
    "reviewed_at" timestamp with time zone,
    "rejection_reason" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "member_change_requests_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'approved'::"text", 'rejected'::"text"])))
);

ALTER TABLE "public"."member_change_requests" OWNER TO "postgres";

DO $$
BEGIN
  ALTER TABLE "public"."member_change_requests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
      SEQUENCE NAME "public"."member_change_requests_id_seq"
      START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  );
EXCEPTION WHEN duplicate_table THEN
  NULL;
END $$;

ALTER TABLE "public"."member_change_requests" DROP CONSTRAINT IF EXISTS "member_change_requests_pkey";
ALTER TABLE ONLY "public"."member_change_requests" ADD CONSTRAINT "member_change_requests_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."member_change_requests" DROP CONSTRAINT IF EXISTS "member_change_requests_member_id_fkey";
ALTER TABLE ONLY "public"."member_change_requests"
    ADD CONSTRAINT "member_change_requests_member_id_fkey" FOREIGN KEY ("member_id") REFERENCES "public"."members"("MemberIDNo") ON DELETE CASCADE;

ALTER TABLE "public"."member_change_requests" DROP CONSTRAINT IF EXISTS "member_change_requests_requested_by_fkey";
ALTER TABLE ONLY "public"."member_change_requests"
    ADD CONSTRAINT "member_change_requests_requested_by_fkey" FOREIGN KEY ("requested_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;

ALTER TABLE "public"."member_change_requests" DROP CONSTRAINT IF EXISTS "member_change_requests_reviewed_by_fkey";
ALTER TABLE ONLY "public"."member_change_requests"
    ADD CONSTRAINT "member_change_requests_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS "idx_member_change_requests_status" ON "public"."member_change_requests" USING "btree" ("status");
CREATE INDEX IF NOT EXISTS "idx_member_change_requests_member" ON "public"."member_change_requests" USING "btree" ("member_id");
CREATE INDEX IF NOT EXISTS "idx_member_change_requests_created_at" ON "public"."member_change_requests" USING "btree" ("created_at" DESC);


-- ---------- RLS ----------
ALTER TABLE "public"."member_change_requests" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Requesters can submit their own change requests" ON "public"."member_change_requests";
CREATE POLICY "Requesters can submit their own change requests" ON "public"."member_change_requests"
FOR INSERT TO "authenticated"
WITH CHECK ("requested_by" = "auth"."uid"() AND "status" = 'pending');

DROP POLICY IF EXISTS "Requesters can view their own change requests" ON "public"."member_change_requests";
CREATE POLICY "Requesters can view their own change requests" ON "public"."member_change_requests"
FOR SELECT TO "authenticated"
USING ("requested_by" = "auth"."uid"());

DROP POLICY IF EXISTS "Approvers can view all change requests" ON "public"."member_change_requests";
CREATE POLICY "Approvers can view all change requests" ON "public"."member_change_requests"
FOR SELECT TO "authenticated"
USING ("public"."is_admin"() OR "public"."is_moderator"());

DROP POLICY IF EXISTS "Approvers manage change requests" ON "public"."member_change_requests";
CREATE POLICY "Approvers manage change requests" ON "public"."member_change_requests"
FOR UPDATE TO "authenticated"
USING ("public"."is_admin"() OR "public"."is_moderator"())
WITH CHECK ("public"."is_admin"() OR "public"."is_moderator"());

DROP POLICY IF EXISTS "Approvers can delete change requests" ON "public"."member_change_requests";
CREATE POLICY "Approvers can delete change requests" ON "public"."member_change_requests"
FOR DELETE TO "authenticated"
USING ("public"."is_admin"() OR "public"."is_moderator"());

GRANT ALL ON TABLE "public"."member_change_requests" TO "authenticated";
GRANT ALL ON TABLE "public"."member_change_requests" TO "service_role";
GRANT ALL ON SEQUENCE "public"."member_change_requests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."member_change_requests_id_seq" TO "service_role";


-- Moderators need to read the same audit_log the new Member Change History
-- page queries (filtered client-side to table_name = 'members') -- the
-- existing "Admins can view audit log" policy stays untouched; this is an
-- additional permissive policy, and Postgres RLS OR's them together.
DROP POLICY IF EXISTS "Moderators can view audit log" ON "public"."audit_log";
CREATE POLICY "Moderators can view audit log" ON "public"."audit_log"
FOR SELECT TO "authenticated"
USING ("public"."is_moderator"());


-- ---------- Register the two new pages ----------
INSERT INTO "public"."pages" ("key", "label", "sort_order") VALUES
    ('memberChangeQueue', 'Change Requests', 16),
    ('memberChangeHistory', 'Member Change History', 17)
ON CONFLICT ("key") DO NOTHING;

INSERT INTO "public"."role_pages" ("role_id", "page_key")
SELECT "id", page_key
FROM "public"."roles", (VALUES ('memberChangeQueue'), ('memberChangeHistory')) AS pk(page_key)
WHERE "name" IN ('Admin', 'Moderator')
ON CONFLICT DO NOTHING;


-- ---------- Realtime ----------
DO $$
BEGIN
  ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."member_change_requests";
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;
