-- =========================================================================
-- Admin accounts, dynamic roles, per-role page access, and the Area
-- (Sector > Cluster > Chapter) hierarchy.
--
-- Run this whole script once in the Supabase SQL editor.
--
-- Portal login accounts (including the very first Admin) are still created
-- manually in Supabase Studio -> Authentication -> Add User; the app has no
-- sign-up screen and holds no service_role key. The trigger below
-- auto-creates a "public.profiles" row the moment that auth user exists;
-- an existing Admin then assigns it a role from the new Administration
-- screen. See the bootstrap step at the bottom of this file to promote the
-- very first Admin (nobody can be promoted through the UI until one exists).
-- =========================================================================


-- ---------- Dynamic roles ----------
CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "roles_name_key" UNIQUE ("name")
);

ALTER TABLE "public"."roles" OWNER TO "postgres";

ALTER TABLE "public"."roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");


-- ---------- Portal user profiles (one row per Supabase Auth user) ----------
CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "email" "text",
    "full_name" "text",
    "role_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "profiles_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "public"."profiles" OWNER TO "postgres";

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE SET NULL;


-- ---------- Page registry (keys match NAV_ITEMS in src/app/index.js) ----------
CREATE TABLE IF NOT EXISTS "public"."pages" (
    "key" "text" NOT NULL,
    "label" "text" NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    CONSTRAINT "pages_pkey" PRIMARY KEY ("key")
);

ALTER TABLE "public"."pages" OWNER TO "postgres";


-- ---------- Per-role page access ----------
CREATE TABLE IF NOT EXISTS "public"."role_pages" (
    "role_id" bigint NOT NULL,
    "page_key" "text" NOT NULL,
    CONSTRAINT "role_pages_pkey" PRIMARY KEY ("role_id", "page_key"),
    CONSTRAINT "role_pages_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE CASCADE,
    CONSTRAINT "role_pages_page_key_fkey" FOREIGN KEY ("page_key") REFERENCES "public"."pages"("key") ON DELETE CASCADE
);

ALTER TABLE "public"."role_pages" OWNER TO "postgres";


-- ---------- Areas: self-referential Sector > Cluster > Chapter tree ----------
-- One head per area (head_member_id); a member may head, or simply belong
-- under, more than one area at a time.
CREATE TABLE IF NOT EXISTS "public"."areas" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "type" "text" NOT NULL,
    "parent_id" bigint,
    "head_member_id" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "areas_type_check" CHECK (("type" = ANY (ARRAY['Sector'::"text", 'Cluster'::"text", 'Chapter'::"text"])))
);

ALTER TABLE "public"."areas" OWNER TO "postgres";

ALTER TABLE "public"."areas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."areas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."areas"
    ADD CONSTRAINT "areas_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."areas"
    ADD CONSTRAINT "areas_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."areas"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."areas"
    ADD CONSTRAINT "areas_head_member_id_fkey" FOREIGN KEY ("head_member_id") REFERENCES "public"."members"("MemberIDNo") ON DELETE SET NULL;

CREATE INDEX "idx_areas_parent" ON "public"."areas" USING "btree" ("parent_id");


-- ---------- Members assigned under an Area ----------
CREATE TABLE IF NOT EXISTS "public"."area_members" (
    "id" bigint NOT NULL,
    "area_id" bigint NOT NULL,
    "member_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."area_members" OWNER TO "postgres";

ALTER TABLE "public"."area_members" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."area_members_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."area_members"
    ADD CONSTRAINT "area_members_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."area_members"
    ADD CONSTRAINT "area_members_area_id_fkey" FOREIGN KEY ("area_id") REFERENCES "public"."areas"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."area_members"
    ADD CONSTRAINT "area_members_member_id_fkey" FOREIGN KEY ("member_id") REFERENCES "public"."members"("MemberIDNo") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."area_members"
    ADD CONSTRAINT "area_members_area_id_member_id_key" UNIQUE ("area_id", "member_id");

CREATE INDEX "idx_area_members_area" ON "public"."area_members" USING "btree" ("area_id");
CREATE INDEX "idx_area_members_member" ON "public"."area_members" USING "btree" ("member_id");


-- ---------- is_admin() helper ----------
-- SECURITY DEFINER so it can read profiles/roles regardless of the calling
-- user's own RLS grants, without recursing back through those tables'
-- policies (search_path is pinned to avoid hijacking).
CREATE OR REPLACE FUNCTION "public"."is_admin"()
RETURNS boolean
LANGUAGE "sql"
SECURITY DEFINER
SET "search_path" = 'public'
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    JOIN public.roles r ON r.id = p.role_id
    WHERE p.id = auth.uid() AND r.name = 'Admin'
  );
$$;

ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";


-- ---------- Auto-create a profile row for every new auth user ----------
CREATE OR REPLACE FUNCTION "public"."handle_new_user"()
RETURNS "trigger"
LANGUAGE "plpgsql"
SECURITY DEFINER
SET "search_path" = 'public'
AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

DROP TRIGGER IF EXISTS "on_auth_user_created" ON "auth"."users";
CREATE TRIGGER "on_auth_user_created"
    AFTER INSERT ON "auth"."users"
    FOR EACH ROW EXECUTE FUNCTION "public"."handle_new_user"();

-- Backfill profiles for any auth users that already existed before this
-- migration ran.
INSERT INTO "public"."profiles" ("id", "email")
SELECT "id", "email" FROM "auth"."users"
ON CONFLICT ("id") DO NOTHING;


-- ---------- Seed roles & pages ----------
-- Safe to re-run even if an earlier version of this script already ran:
-- drops the old single "admin" page and the Admin role's old blanket grant
-- so this always converges on the page set/grants below.
DELETE FROM "public"."role_pages" WHERE "role_id" = (SELECT "id" FROM "public"."roles" WHERE "name" = 'Admin');
DELETE FROM "public"."pages" WHERE "key" = 'admin';

INSERT INTO "public"."roles" ("name", "description") VALUES
    ('Admin', 'Manages portal users, roles, page access, and the Area hierarchy. Grant data pages via other roles.')
ON CONFLICT ("name") DO NOTHING;

INSERT INTO "public"."pages" ("key", "label", "sort_order") VALUES
    ('home', 'Dashboard', 1),
    ('members', 'Directory', 2),
    ('pfo', 'PFO Trainings', 3),
    ('pfoReports', 'PFO Reports', 4),
    ('pfoStats', 'Formation Stats', 5),
    ('clp', 'CLP Maintenance', 6),
    ('auditLogs', 'Audit Logs', 7),
    ('portalUsers', 'Portal Users', 8),
    ('rolesAccess', 'Roles & Page Access', 9),
    ('areas', 'Areas', 10)
ON CONFLICT ("key") DO NOTHING;

-- The Admin role has no built-in "sees everything" bypass in the app (see
-- src/lib/access.js) — its visible pages are just whatever is checked here,
-- same as any other role. Seed it with only the administrative pages, not
-- the day-to-day data-entry ones; grant those to other roles as needed from
-- the Roles & Page Access screen.
INSERT INTO "public"."role_pages" ("role_id", "page_key")
SELECT (SELECT "id" FROM "public"."roles" WHERE "name" = 'Admin'), "key"
FROM "public"."pages"
WHERE "key" IN ('auditLogs', 'portalUsers', 'rolesAccess', 'areas')
ON CONFLICT DO NOTHING;


-- ---------- Row Level Security ----------
ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."pages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."role_pages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."areas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."area_members" ENABLE ROW LEVEL SECURITY;

-- profiles: any signed-in user can see the roster of portal users (needed
-- to render the Portal Users list and member/area head pickers); a user
-- may edit their own display name; only Admins may change roles or remove
-- a profile.
CREATE POLICY "Authenticated can view profiles" ON "public"."profiles" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Users can update own profile" ON "public"."profiles" FOR UPDATE TO "authenticated" USING ("id" = "auth"."uid"()) WITH CHECK ("id" = "auth"."uid"());
CREATE POLICY "Admins can update any profile" ON "public"."profiles" FOR UPDATE TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());
CREATE POLICY "Admins can delete profiles" ON "public"."profiles" FOR DELETE TO "authenticated" USING ("public"."is_admin"());

-- roles / pages / role_pages: readable by every signed-in user (needed to
-- compute their own nav visibility), writable only by Admins.
CREATE POLICY "Authenticated can view roles" ON "public"."roles" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Admins manage roles" ON "public"."roles" FOR ALL TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());

CREATE POLICY "Authenticated can view pages" ON "public"."pages" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Admins manage pages" ON "public"."pages" FOR ALL TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());

CREATE POLICY "Authenticated can view role_pages" ON "public"."role_pages" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Admins manage role_pages" ON "public"."role_pages" FOR ALL TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());

-- areas / area_members: readable by every signed-in user, writable only by
-- Admins.
CREATE POLICY "Authenticated can view areas" ON "public"."areas" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Admins manage areas" ON "public"."areas" FOR ALL TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());

CREATE POLICY "Authenticated can view area_members" ON "public"."area_members" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Admins manage area_members" ON "public"."area_members" FOR ALL TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());


-- ---------- Grants ----------
-- Deliberately no "anon" grants here (unlike members/clp_*): none of this
-- is part of the public training-lookup/self-registration surface.
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";

GRANT ALL ON TABLE "public"."roles" TO "authenticated";
GRANT ALL ON TABLE "public"."roles" TO "service_role";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."pages" TO "authenticated";
GRANT ALL ON TABLE "public"."pages" TO "service_role";

GRANT ALL ON TABLE "public"."role_pages" TO "authenticated";
GRANT ALL ON TABLE "public"."role_pages" TO "service_role";

GRANT ALL ON TABLE "public"."areas" TO "authenticated";
GRANT ALL ON TABLE "public"."areas" TO "service_role";
GRANT ALL ON SEQUENCE "public"."areas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."areas_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."area_members" TO "authenticated";
GRANT ALL ON TABLE "public"."area_members" TO "service_role";
GRANT ALL ON SEQUENCE "public"."area_members_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."area_members_id_seq" TO "service_role";


-- =========================================================================
-- BOOTSTRAP THE FIRST ADMIN (manual, one-time)
--
-- 1. Supabase Studio -> Authentication -> Add User, create yourself an
--    account (email + password).
-- 2. Come back here and run the statement below with that email, so you
--    have an Admin account to sign in with and promote everyone else from
--    the new Administration screen:
--
-- UPDATE "public"."profiles" SET "role_id" = (SELECT "id" FROM "public"."roles" WHERE "name" = 'Admin')
-- WHERE "email" = 'you@example.com';
-- =========================================================================
