-- =========================================================================
-- Adds formation_stats_snapshots: point-in-time captures of the Formation
-- Stats screen's numbers, so completion rates can be compared over time
-- instead of only ever showing a live "right now" snapshot.
--
-- Each row stores the filter context (Area/Roles) it was computed under
-- and every track's result as JSONB -- storing the computed numbers
-- (rather than re-deriving historical values later from members/
-- pfo_members, which only ever reflect CURRENT state) is what makes this
-- an actual point-in-time record instead of just another live query.
--
-- Run once. Safe to re-run.
-- =========================================================================

CREATE TABLE IF NOT EXISTS "public"."formation_stats_snapshots" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_by" "uuid",
    "created_by_email" "text",
    "note" "text",
    "area_filter" "text" DEFAULT 'All' NOT NULL,
    "role_filter" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "total_members" integer DEFAULT 0 NOT NULL,
    "track_results" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL
);

ALTER TABLE "public"."formation_stats_snapshots" OWNER TO "postgres";

DO $$
BEGIN
  ALTER TABLE "public"."formation_stats_snapshots" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
      SEQUENCE NAME "public"."formation_stats_snapshots_id_seq"
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1
  );
EXCEPTION WHEN duplicate_table THEN
  NULL;
END $$;

ALTER TABLE "public"."formation_stats_snapshots" DROP CONSTRAINT IF EXISTS "formation_stats_snapshots_pkey";
ALTER TABLE ONLY "public"."formation_stats_snapshots" ADD CONSTRAINT "formation_stats_snapshots_pkey" PRIMARY KEY ("id");

CREATE INDEX IF NOT EXISTS "idx_formation_stats_snapshots_created_at" ON "public"."formation_stats_snapshots" USING "btree" ("created_at" DESC);

ALTER TABLE "public"."formation_stats_snapshots" ENABLE ROW LEVEL SECURITY;

-- Same broad "any signed-in account" trust level as members/pfo_members --
-- page-level access (the 'pfoStats' page grant) is what actually gates who
-- reaches this screen at all.
DROP POLICY IF EXISTS "Authenticated can view formation stats snapshots" ON "public"."formation_stats_snapshots";
CREATE POLICY "Authenticated can view formation stats snapshots" ON "public"."formation_stats_snapshots"
FOR SELECT TO "authenticated"
USING (true);

DROP POLICY IF EXISTS "Authenticated can save formation stats snapshots" ON "public"."formation_stats_snapshots";
CREATE POLICY "Authenticated can save formation stats snapshots" ON "public"."formation_stats_snapshots"
FOR INSERT TO "authenticated"
WITH CHECK (true);

GRANT ALL ON TABLE "public"."formation_stats_snapshots" TO "authenticated";
GRANT ALL ON TABLE "public"."formation_stats_snapshots" TO "service_role";
GRANT ALL ON SEQUENCE "public"."formation_stats_snapshots_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."formation_stats_snapshots_id_seq" TO "service_role";
